name: Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  get_notebooks:
    name: Get list of notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LION repo
        uses: actions/checkout@v6

      - id: set-matrix
        run: |
          echo "notebook_paths=$(find examples/notebooks -type f -name '*.ipynb' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Notebook overview
        run: |
          echo "jupyter-notebooks: ${{ steps.set-matrix.outputs.notebook_paths }}"

    outputs:
      notebook_paths: ${{ steps.set-matrix.outputs.notebook_paths }}

  create_documentation:
    name: Build and deploy documentation
    needs: get_notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetch history for github links
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install LION and dependencies
        run: pip install -e .[docs]

      - name: Download executed notebook ipynb files
        id: download
        uses: actions/download-artifact@v6
        with:
          path: ./docs/source/_notebooks/
          merge-multiple: true

      - name: Build docs
        run: |
          sphinx-build -b html ./docs/source ./docs/build/html
          rm -rf ./docs/build/html/.doctrees

      - name: Upload documentation artifact
        id: upload_docs
        uses: actions/upload-artifact@v5
        with:
          name: Documentation
          path: docs/build/html/

      # if the one of above steps fails the "artifact-url" will be an empty string
      - name: Dump documentation info
        if: always()
        run: |
          echo "${{ steps.upload_docs.outputs.artifact-url }}" > artifact_url

      - name: Upload docs-metadata artifact
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: artifact_url
          path: artifact_url

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
