name: Manual Hello

on:
  push:
    branches:
      - general_op_and_pcm_with_notebooks
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello World"
